#!/usr/bin/env python3

import sys
import argparse
from os.path import dirname, realpath
import yaml

###################### OPEN CONFIG FILE ######################
# directory containing config.yaml
rootdir = dirname(realpath(__file__))
try:
    with open(rootdir+'/config.yaml', 'r') as config_file:
        try:
            config = yaml.safe_load(config_file)
        except yaml.YAMLError as exception:
            print('Invalid YAML configuration file; '
                  'please check syntax.')
            print(str(exception)+' '+sys.exc_info())
            exit(-1)
except:
    print('Pipeline unable to locate config.yaml; '
          'please make sure that it exists.')
    print(sys.exc_info())
    exit(-1)


########################## COMMAND LINE PARSER ########################
parser = argparse.ArgumentParser(prog='atlas',
                                 description='Manage '+config['general']['name'])
parser.add_argument('--start-all', '-a', action='store_true',
                    default='True', help='Start all components')
parser.add_argument('--start-pipeline', '-p', action='store_true',
                    default='True', help='Start the pipeline server')
parser.add_argument('--start-queue', '-q', action='store_true',
                    default='True', help='Start the queue server')
parser.add_argument('--start-mqtt', '-m', action='store_true',
                    default='True', help='Start the MQTT messaging broker')
parser.add_argument('--start-telescope', '-t', action='store_true',
                    default='True', help='Start the telescope control server')
parser.add_argument('--start-logging', '-l', action='store_true',
                    default='True', help='Start the logging server')
parser.add_argument('--start-web', '-w', action='store_true',
                    default='True', help='Start the web application')
parser.add_argument('--version', action='version', version='%(prog)s 0.0.1')

####################### PARSE COMMAND LINE ARGS ####################
args = parser.parse_args()
