#!/usr/bin/env python3
import argparse
import os
import sys
from os.path import dirname, realpath
import json
import yaml

from imqueue import executor


#################### CREATE COMMAND LINE ARGUMENT PARSER #######################
parser = argparse.ArgumentParser(description='Manually start an executor with a given queue file')
parser.add_argument( '--queue', help="The queue file to execute", required=True, type=str)

######################### PARSE COMMAND LINE ARGUMENTS #########################
args = parser.parse_args()

######################### IMPORT CONFIGURATION PARAMETERS ######################
config_dir = dirname(dirname(realpath(__file__))) ## locate file containing config
try:
    with open(config_dir+"/config.yaml", 'r') as config_file:
        try:
            config = yaml.safe_load(config_file)
        except yaml.YAMLError as exception:
            print("\033[1;31mInvalid YAML configuration file; please check syntax...\033[0m")
            print(sys.exc_info())
            exit(-1)
except:
    print("\033[1;31mUnable to locate config.yaml; please make sure that it exists...\033[0m")
    print(sys.exc_info())
    exit(-1)


# create an executor and start it executing
exec = executor.Executor(args.q, config)
exec.start()
