#!/usr/bin/env python3
import argparse
import paho.mqtt.client as mqtt
import os
import sys
from os.path import dirname, realpath
import json
import yaml

#################### CREATE COMMAND LINE ARGUMENT PARSER #######################
parser = argparse.ArgumentParser(description='Publish messages to any topic on the server')
parser.add_argument('--message', '-m', help="The message to be sent", type=str, required=True)
parser.add_argument('--topic', '-t', help="The topic for the message", type=str, required=True)


######################### PARSE COMMAND LINE ARGUMENTS #########################
args = parser.parse_args()


######################### IMPORT CONFIGURATION PARAMETERS ######################
config_dir = dirname(dirname(realpath(__file__))) ## locate file containing config
try:
    with open(config_dir+"/config.yaml", 'r') as config_file:
        try:
            config = yaml.safe_load(config_file)
        except yaml.YAMLError as exception:
            print("\033[1;31mInvalid YAML configuration file; please check syntax...\033[0m")
            print(sys.exc_info())
            exit(-1)
except:
    print("\033[1;31mUnable to locate config.yaml; please make sure that it exists...\033[0m")
    print(sys.exc_info())
    exit(-1)

    
######################### CONNECT TO STONE EDGE SERVER #########################

# mqtt client to handle connection
client = mqtt.Client()

# connect to stone edge observatory
try:
    client.connect(config['server']['host'], config['mosquitto']['port'], 60)
    self.__log('Successfully connected to '+config['general']['name'], color='green')
except:
    self.__log('Unable to connect to '+config['general']['name']+'. Please try again later. '
               'If the problem persists, please contact '+config['general']['email'], 'red')
    print(sys.exc_info())
    exit(-1)


###################### SEND REQUEST TO STONE EDGE SERVER #######################
try:
    client.publish(args.topic, args.message)
    print('\033[1;32mMessage successfully published!\033[0m')
except:
    print('\033[1;31mUnable to publish message to server. '
          'Please contact '+config['general']['email']+'\033[0m')
    print(sys.exc_info())
    exit(-1)
    
